###docker-compose for visualization for SETO project by UNCC
#Author: Bodo Baumann
#Github: https://github.com/Sarkspasst

######################################

#Change passwords, user, etc. in .env
#Change postgresql configuration in customPostgresql.conf
services:

  #Database for all SETO visualization data
  seto_db:
    image: postgres:16
    command: -c config_file=/etc/postgresql.conf
    volumes:
      # Initialize the POSTGRES_MULTIPLE_DATABASES environment
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      # Load custom postgresql configuration
      - ./customPostgresql.conf:/etc/postgresql.conf
      # The directory "./logs" is created by run.sh on the host. Postgres is configured via customPostgresql.conf to write log messages to "/logs"
      - ./logs:/logs
      #Add the database files to the host
      #- ./seto_data:/var/lib/postgresql/data
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: setomatlabdb,setoopendssdb,setocomparisondb #${DB_NAMES}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  # Database to store Grafana metadata
  gf_db:
    image: postgres:15
    container_name: ${GF_DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${GF_DB_PORT}:5432"
    environment:
      POSTGRES_HOST: ${GF_DB_HOST}
      POSTGRES_DB: ${GF_DB_DATABASE}
      POSTGRES_USER: ${GF_DB_USER}
      POSTGRES_PASSWORD: ${GF_DB_PASSWORD}
    volumes:
      - gf_db:/var/lib/postgresql/data #Store the database on the host

  seto_gf:
    image: grafana/grafana:latest
    container_name: ${GF_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${GF_PORT}:3000
    user: "0:0"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      #From gf_db
      GF_DATABASE_TYPE: ${GF_DB_TYPE}
      GF_DATABASE_HOST: ${GF_DB_CONTAINER_NAME}:5432
      GF_DATABASE_NAME: ${GF_DB_DATABASE}
      GF_DATABASE_USER: ${GF_DB_USER}
      GF_DATABASE_PASSWORD: ${GF_DB_PASSWORD}
      GF_DATABASE_SSL_MODE: ${GF_DB_SSL_MODE}
      #GF_INSTALL_PLUGINS: grafana-worldmap-panel, citilogics-geoloop-panel
    depends_on:
        - gf_db
    volumes:
      - seto_gf:/var/lib/grafana

  #Just for SQL-DB monitoring
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

volumes:
  gf_db:
    driver: local
  seto_gf:
    driver: local
  seto_db:
    driver: local